# Uncomment the next line to define a global platform for your project
platform :ios, '14.1'

target 'iOSHost' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOSHost

  pod 'shared', :path => '/Users/quba/Repo/kmm_demo/module/shared/shared.podspec'

  target 'iOSHostTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOSHostUITests' do
    # Pods for testing
  end

end
